#!/bin/bash
#
# @@script: backup.sh
# @@description: equilibrium main run script
# @@author: Loouis Low (loouis@gmail.com)
# @@copyright: Loouis Low (https://github.com/loouislow81/equilibrium)
# @@license: MIT
#

###### imports ######

source /etc/equilibrium.conf

###### funcs ######

run_as_root() {
  if [ "$(whoami &2> /dev/null)" != "root" ] &&
     [ "$(id -un &2> /dev/null)" != "root" ]; then
    echo -e "$title permission denied.";echo
    exit 1
  fi
}

function copy_files() {
  #--- arg
  files=$1
  copy_to_destination=$2
  #--- arr
  get_files=($files)
  #--- worker
  for w in "${get_files[@]}"; do
    cp -r $PWD/${w} ${copy_to_destination}
    echo -e "$title ${w} copied to $arrow ${copy_to_destination} (OK)"
  done
}

create_marker() {
  echo -e "$title create backup marker..."
  mkdir -p "$BACKUP_DESTINATION"
  touch "$BACKUP_DESTINATION/backup.marker"
}

run_backup() {
  echo -e "$title started..."
  equilibrium-core ${BACKUP_SOURCE} ${BACKUP_DESTINATION}
  echo -e "$title backup $arrow done!"
}

banner() {
  echo -e "${blue}                   _ _ _ _          _                 "
  echo -e "                  (_) (_) |        (_)                "
  echo -e "   ___  __ _ _   _ _| |_| |__  _ __ _ _   _ _ __ ___  "
  echo -e "  / _ \/ _' | | | | | | | '_ \| '__| | | | | '_ ' _ \ "
  echo -e " |  __/ (_| | |_| | | | | |_) | |  | | |_| | | | | | |"
  echo -e "  \___|\__, |\__,_|_|_|_|_.__/|_|  |_|\__,_|_| |_| |_|"
  echo -e "          | |                                         "
  echo -e "          |_|${normal}";echo
}

###### init ######

banner
echo -e "${bold} $ backup [--help|--install|--run|--exclusion|--config] ${normal}";echo

while test "$#" -gt 0; do
  case "$1" in

    -h|--help)
    shift
      echo;echo -e " ${bold}Usage:${normal}"
      echo -e "   -h, --help .................. Display this information"
      echo -e "   -i, --install ............... Install to your system"
      echo -e "   -r, --run ................... Run/Resume backup session"
      echo -e "   -e, --exclusion ............. Edit exclusion list"
      echo -e "   -c, --config ................ Edit settings";echo
      echo -e " ${bold}Utility:${normal}"
      echo -e "   -l, --show-log .............. Show log files"
      echo -e "   -p, --purge-log ............. Purge log files";echo
      echo -e " Visit repository $arrow (https://github.com/loouislow81/equilibrium)"
      echo -e " Submit issue $arrow (https://github.com/loouislow81/equilibrium/issues)";echo
      exit 1
    shift;;

    -i|--install)
    shift
      run_as_root
      copy_files "backup equilibrium-core" "/usr/local/bin/"
      copy_files "equilibrium.conf equilibrium-exclusion.list" "/etc/"
    shift;;

    -r|--run)
    shift
      run_as_root
      create_marker
      run_backup
    shift;;

    -e|--exclusion)
    shift
      run_as_root
      nano /etc/equilibrium-exclusion.list
      echo -e "$title (?) exclusion list is in $arrow /etc/equilibrium-exclusion.list";echo
    shift;;

    -c|--config)
    shift
      run_as_root
      nano /etc/equilibrium.conf
      echo -e "$title (?) setting file is in $arrow /etc/equilibrium.conf";echo
    shift;;

    -l|--show-log)
    shift
      cd $HOME/.equilibrium-core
      ls -l
    shift;;

    -p|--purge-log)
    shift
      run_as_root
      rm -rfv $HOME/.equilibrium-core/*
    shift;;

    *) break;;

  esac
done
